Repository SymfonyCasts/verify-email-bundle, pull requests merged in 2020-12, with the labels that each got.

#42 Allow installation with PHP8, add Symfony 5.2 to tests
  .github/workflows/ci.yml
  composer.json
Labels: status: reviewed

#45 PHP 8 support in CI / Dev
  .github/workflows/ci.yml
  composer.json
  psalm.xml
Labels: CI

#43 improve signature expiration support
  CHANGELOG.md
  composer.json
  src/Model/VerifyEmailSignatureComponents.php
  src/Resources/translations/VerifyEmailBundle.en.xlf
  src/VerifyEmailHelper.php
  tests/UnitTests/Model/VerifyEmailSignatureComponentsTest.php
Labels: bug, enhancement, status: needs review
