Repository SymfonyCasts/verify-email-bundle, pull requests merged in 2022-07, with the labels that each got.

#118 Add catalan translations
  src/Resources/translations/VerifyEmailBundle.ca.xlf
Labels: status: reviewed, Feature

#121 Add missing target-language attr to all translations
  src/Resources/translations/VerifyEmailBundle+intl-icu.nl.xlf
  src/Resources/translations/VerifyEmailBundle.cs.xlf
  src/Resources/translations/VerifyEmailBundle.de.xlf
  src/Resources/translations/VerifyEmailBundle.en.xlf
  src/Resources/translations/VerifyEmailBundle.es.xlf
  src/Resources/translations/VerifyEmailBundle.it.xlf
  src/Resources/translations/VerifyEmailBundle.pl.xlf
  src/Resources/translations/VerifyEmailBundle.pt.xlf
  src/Resources/translations/VerifyEmailBundle.ro.xlf
  src/Resources/translations/VerifyEmailBundle.ru.xlf
  src/Resources/translations/VerifyEmailBundle.sk.xlf
  src/Resources/translations/VerifyEmailBundle.sr.xlf
  src/Resources/translations/VerifyEmailBundle.tr.xlf
  src/Resources/translations/VerifyEmailBundle.uk.xlf
Labels: Feature

#122 [ci] global flex is not needed here
  .github/workflows/ci.yml
Labels: status: needs review, Minor

#123 [ci] php-cs-fixer it up
  src/Util/VerifyEmailQueryUtility.php
  tests/AcceptanceTests/VerifyEmailAcceptanceTest.php
  tests/UnitTests/Generator/VerifyEmailTokenGeneratorTest.php
Labels: Minor

#124 [git-released] v1.11.0
  CHANGELOG.md
Labels: Minor
