Repository SymfonyCasts/verify-email-bundle, pull requests merged in 2024-03, with the labels that each got.

#160 [2.x] version bumps
  .github/workflows/ci.yaml
  composer.json
Labels: Status: Needs Work, Feature

#157 [1.x] use `UriSigner::checkRequest()` to validate signatures using a `Request` object
  src/Util/VerifyEmailQueryUtility.php
  src/VerifyEmailHelper.php
  src/VerifyEmailHelperInterface.php
  tests/AcceptanceTests/VerifyEmailAcceptanceTest.php
  tests/FunctionalTests/VerifyEmailHelperFunctionalTest.php
  tests/IntegrationTests/VerifyEmailBundleAutowireTest.php
  tests/IntegrationTests/VerifyEmailServiceDefinitionTest.php
  tests/UnitTests/Util/VerifyEmailQueryTest.php
  tests/UnitTests/VerifyEmailHelperTest.php
Labels: Status: Reviewed, Status: Needs Review, Feature

#165 [1.x] UriSigner to become internal in 2.x
  UPGRADING.md
  src/Factory/UriSignerFactory.php
Labels: Status: Needs Review, Feature

#164 [2.x] inject UriSigner directly in the VerifyEmailHelper
  src/Factory/UriSignerFactory.php
  src/Resources/config/verify_email_services.xml
  src/VerifyEmailHelper.php
  tests/IntegrationTests/VerifyEmailServiceDefinitionTest.php
Labels: Feature

#167 [2.x][tests] remove legacy tests and cleanup
  tests/AcceptanceTests/VerifyEmailAcceptanceTest.php
  tests/FunctionalTests/VerifyEmailHelperFunctionalTest.php
  tests/IntegrationTests/VerifyEmailBundleAutowireTest.php
  tests/IntegrationTests/VerifyEmailServiceDefinitionTest.php
  tests/UnitTests/VerifyEmailHelperTest.php
  tests/VerifyEmailTestKernel.php
Labels: CI, Minor

#166 [2.x] generatedAt is now required
  UPGRADING.md
  src/Model/VerifyEmailSignatureComponents.php
Labels: Feature

#168 [2.x] remove potential `LogicException` from translation methods
  UPGRADING.md
  src/Model/VerifyEmailSignatureComponents.php
Labels: Feature

#143 Updating docs for latest generated code from MakerBundle
  README.md
Labels: Minor

#170 [upgrade] document validateEmailConfirmationFromRequest
  UPGRADING.md
Labels: documentation, Minor

#171 RegistrationController uses constructor property promotion
  README.md
Labels: documentation, Minor

#169 [release] v1.17.0
  CHANGELOG.md
Labels: Status: Needs Work, Feature

#163 [2.x] refactor to use php 8.3 features
  src/Generator/VerifyEmailTokenGenerator.php
  src/Model/VerifyEmailSignatureComponents.php
  src/VerifyEmailHelper.php
  tests/VerifyEmailTestKernel.php
Labels: Feature

#174 Add Danish translations
  src/Resources/translations/VerifyEmailBundle.da.xlf
Labels: Status: Reviewed, Feature
